[base]
name = netsalt
testdeps =
    mock
    pytest

[tox]
envlist =
    lint
    py{310,311,312}
    docs

minversion = 3.1.0

# ignore basepython for envs that already specify a version
ignore_basepython_conflict = true

[testenv]
deps = {[base]testdeps}
commands = pytest

[testenv:lint]
basepython = python3
deps = ruff
commands =
    ruff check netsalt tests
    ruff format --check netsalt tests

[testenv:format]
deps = ruff
commands =
    ruff check --fix netsalt tests
    ruff format netsalt tests

[testenv:docs]
changedir = doc
deps =
    sphinx
    alabaster
commands = make html
allowlist_externals = make

[gh-actions]
python =
  3.10: py310, lint
  3.11: py311
  3.12: py312

